---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: ${{values.artifact_id}}
  labels:
    apps.kadras.io/workload-type: web
    apps.kadras.io/language: java
    apps.kadras.io/has-tests: "true"
    app.kubernetes.io/part-of: ${{values.artifact_id}}
spec:
  source:
    git:
      url: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}
      ref:
        branch: main
  build:
    env: 
      - name: BP_JVM_VERSION 
        value: "17"
